<a href="https://colab.research.google.com/github/mohamedelgawish511-bot/ai-platform-assigments/blob/main/aiplatform_assigment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import torch


in_features = 4
x = torch.randn(1, in_features)

x.requires_grad_()

print(f"▶ Input (x):\n{x}\n")


w0 = torch.randn(3, in_features, requires_grad=True)
b0 = torch.randn(3, requires_grad=True)


w1 = torch.randn(2, in_features, requires_grad=True)
b1 = torch.randn(2, requires_grad=True)


w2 = torch.randn(1, 5, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)



print("--- Starting Forward Pass ---")


print("\n--- Path 1: Layer 1 (ReLU) ---")
z1 = x @ w0.T + b0
a1 = torch.relu(z1)
print(f"Intermediate Output (z1):\n{z1}")
print(f"Activation Output (a1):\n{a1}")



print("\n--- Path 2: Layer 2 (Sigmoid) ---")
z2 = x @ w1.T + b1
a2 = torch.sigmoid(z2)
print(f"Intermediate Output (z2):\n{z2}")
print(f"Activation Output (a2):\n{a2}")



print("\n--- Combination Step (Concatenate & Tanh) ---")

a_cat = torch.cat((a1, a2), dim=1)
a_comb = torch.tanh(a_cat)
print(f"Concatenated Output (a_cat):\n{a_cat}")
print(f"Activation Output (a_comb):\n{a_comb}")



print("\n--- Output Layer (Linear) ---")

y_final = a_comb @ w2.T + b2
print(f"✅ Final Output (y):\n{y_final}")

print("\n--- Forward Pass Complete ---\n")



print("--- Starting Backward Pass ---")
y_final.backward()
print("--- Backward Pass Complete ---\n")




print(f"🔥 Gradient of output w.r.t input (dy/dx):\n{x.grad}")

▶ Input (x):
tensor([[-0.4668,  0.6966, -0.6581,  0.3906]], requires_grad=True)

--- Starting Forward Pass ---

--- Path 1: Layer 1 (ReLU) ---
Intermediate Output (z1):
tensor([[-1.7725, -0.0336,  0.0702]], grad_fn=<AddBackward0>)
Activation Output (a1):
tensor([[0.0000, 0.0000, 0.0702]], grad_fn=<ReluBackward0>)

--- Path 2: Layer 2 (Sigmoid) ---
Intermediate Output (z2):
tensor([[1.8574, 0.4225]], grad_fn=<AddBackward0>)
Activation Output (a2):
tensor([[0.8650, 0.6041]], grad_fn=<SigmoidBackward0>)

--- Combination Step (Concatenate & Tanh) ---
Concatenated Output (a_cat):
tensor([[0.0000, 0.0000, 0.0702, 0.8650, 0.6041]], grad_fn=<CatBackward0>)
Activation Output (a_comb):
tensor([[0.0000, 0.0000, 0.0700, 0.6988, 0.5399]], grad_fn=<TanhBackward0>)

--- Output Layer (Linear) ---
✅ Final Output (y):
tensor([[0.3230]], grad_fn=<AddBackward0>)

--- Forward Pass Complete ---

--- Starting Backward Pass ---
--- Backward Pass Complete ---

🔥 Gradient of output w.r.t input (dy/dx):
tensor([

In [11]:

import torch
import torch.nn as nn


in_features = 4


class CustomNet(nn.Module):

    def __init__(self, in_features):

        super().__init__()


        self.layer1 = nn.Linear(in_features, 3)
        self.layer2 = nn.Linear(in_features, 2)
        self.output_layer = nn.Linear(5, 1)


    def forward(self, x):
        a1 = torch.relu(self.layer1(x))
        a2 = torch.sigmoid(self.layer2(x))
        a_cat = torch.cat((a1, a2), dim=1)
        a_comb = torch.tanh(a_cat)
        final_output = self.output_layer(a_comb)
        return final_output


model = CustomNet(in_features)


print("📜 Model Architecture:")
print(model)
print("-" * 30)


x_input = torch.randn(1, in_features, requires_grad=True)

print("🚀 Running the nn.Module version...")
final_y = model(x_input)
print(f"✅ Final Output (y):\n{final_y}\n")
final_y.backward()


print(f"🔥 Gradient of output w.r.t input (dy/dx):\n{x_input.grad}\n")
print("🔬 Example of parameter gradients (Layer 1 weights):")
print(model.layer1.weight.grad)

📜 Model Architecture:
CustomNet(
  (layer1): Linear(in_features=4, out_features=3, bias=True)
  (layer2): Linear(in_features=4, out_features=2, bias=True)
  (output_layer): Linear(in_features=5, out_features=1, bias=True)
)
------------------------------
🚀 Running the nn.Module version...
✅ Final Output (y):
tensor([[0.0709]], grad_fn=<AddmmBackward0>)

🔥 Gradient of output w.r.t input (dy/dx):
tensor([[ 0.0999, -0.0066, -0.0064,  0.0930]])

🔬 Example of parameter gradients (Layer 1 weights):
tensor([[-0.0000, -0.0000,  0.0000, -0.0000],
        [ 0.1264,  0.1047, -0.1851,  0.1392],
        [-0.0000, -0.0000,  0.0000, -0.0000]])
